Refactor/32
moa-moa-service/moamoa-backend pull request #44
Opened 2024-01-29 09:32 UTC by kellykhy

## <i>PULL REQUEST</i>

### 🎋 작업중인 브랜치
- refactor/32

### 💡 작업동기
- 타 클래스 변경사항 KeywordController 반영안됨.

### 🔑 주요 변경사항
- KeywordController 내 MemberQueryServiceImpl에서 MemberModuleServiceImpl 로 변경

### 관련 이슈
- https://github.com/moa-moa-service/moamoa-backend/issues/32

2024-01-29 09:57 UTC, yjsmk0902 requested changes
계층 리팩토링 중 제가 잊고 누락한 부분이 있었던 것 같습니다. 변경 사항에 대한 코멘트 확인부탁드립니다~!!

2024-01-29 09:57 UTC, yjsmk0902 commented on build.gradle
> +    sourceCompatibility = '21'
컨벤션상 개발 환경은 Java 버전은 17버전입니다.

2024-01-29 09:57 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/web/controller/KeywordController.java
> +    private final MemberModuleServiceImpl memberQueryService;
제가 이전에 pr할때 확인을 못한 부분이 있던 것 같습니다.

컨트롤러 계층에서는 모듈서비스를 사용해서는 안됩니다. 

`keywordQueryService.popularSearchRankList(auth.id());`

이렇게 넘겨서 KeywordQueryService 내부에서 처리해줘야 할 것 같습니다.

2024-02-02 10:01 UTC, kellykhy commented on build.gradle
> +    sourceCompatibility = '21'
넵! 반영해서 고쳐보겠습니다

2024-02-02 10:01 UTC, kellykhy commented on src/main/java/site/moamoa/backend/web/controller/KeywordController.java
> +    private final MemberModuleServiceImpl memberQueryService;
넵 반영해서 고쳐보겠습니다!

2024-02-02 10:12 UTC, closed without merging