🐛 Fix: 공동구매 수정 요청 시, 수정 사항과 이미지를 분리하여 요청 가능하게 개선
moa-moa-service/moamoa-backend pull request #68
Opened 2024-02-09 15:55 UTC by alex052525

## <i>PULL REQUEST</i>

### 🎋 작업중인 브랜치
- fix/63

### 💡 작업동기
- 공동구매 수정 요청 시, 수정 사항과 이미지가 분리되지 않아 요청 시 각각 추가할 수 없는 문제 발생 

### 🔑 주요 변경사항
- 공동구매 수정 API의 요청 바디에서 수정 사항과 이미지를 분리하여 각각 추가할 수 있게함.

### 관련 이슈
https://github.com/moa-moa-service/moamoa-backend/issues/63

2024-02-09 19:06 UTC, shihan00321 approved these changes
👍

2024-02-10 03:26 UTC, yjsmk0902 requested changes
코멘트 확인부탁드립니다~!!

2024-02-10 03:26 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/web/controller/PostController.java
> +    @PatchMapping(value = "/api/posts/{postId}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
해당 부분만 수정뿐아니라 `UpdatePostInfo Request DTO`의 `List<MultipartFile>` 타입으로 존재하는 이미지 필드도 제거가 필요해 보입니다. 확인 한번 부탁드립니다!!

2024-02-10 11:40 UTC, kellykhy approved these changes
확인했습니다!

2024-02-12 07:42 UTC, alex052525 commented on src/main/java/site/moamoa/backend/web/controller/PostController.java
> +    @PatchMapping(value = "/api/posts/{postId}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
확인하고 제거했습니다.

2024-02-12 07:58 UTC, yjsmk0902 approved these changes
👍

2024-02-12 07:58 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/web/controller/PostController.java
> +    @PatchMapping(value = "/api/posts/{postId}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
확인했습니다 👍

2024-02-12 08:04 UTC, merged