Refactor: 공동구매 상세 조회 기능 수정
moa-moa-service/moamoa-backend pull request #71
Opened 2024-02-10 17:19 UTC by shihan00321

## <i>PULL REQUEST</i>

### 🎋 작업중인 브랜치
- refactor/49

### 💡 작업동기
- 채팅 기능 차선책으로 공지사항이 추가됨에 따라 응답 dto를 수정하였습니다.

### 🔑 주요 변경사항
- post 조회 시 공지사항 list 응답 추가
- post 조회 시 쿼리가 너무 많이 보내지게 되어 join으로 한 번에 받아오게 수정

### 관련 이슈
- #49

2024-02-12 07:29 UTC, yjsmk0902 requested changes
`MemberPost` 예외처리의 위치에 관한 이슈가 있습니다.
코멘트 확인 부탁드립니다~!!

2024-02-12 07:29 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
> +                .orElseThrow(
해당 예외는 `MemberPostRepository` 사용시 저수준의 `ModuleService`에서 발생할 수 있는 예외입니다.
따라서 `MemberPostModuleServiceImpl`안에서 처리하는 게 좋지 않을까 생각합니다.

2024-02-12 07:49 UTC, alex052525 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
> +                .orElseThrow(
그런거 같네요. 수정완료했습니다!

2024-02-12 08:03 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
> +                .orElseThrow(
확인했습니다 👍

2024-02-12 08:03 UTC, yjsmk0902 approved these changes

2024-02-12 08:23 UTC, shihan00321 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
> +                .orElseThrow(
원래 처음에는 MemberPostModuleService에서 예외 처리를 했었습니다. 저 부분을 제가 위처럼 수정했었는데 수정한 이유로는  공동구매 상세조회 기능 구현 중에 MemberPost에서 memberId와 postId를 사용해서 이 유저가 참여 중인지 아닌지를 확인해서 공지사항을 가져오는 부분에 대한 로직이 필요했고 마침 저 메서드가 존재해서 사용을 하려 했는데 그러기 위해선 저 메서드에서 해당 유저를 찾지 못하면 예외를 던지는 것이 아니라  optional 타입의 반환이 필요해서 위처럼 수정을 했었습니다. 물론 지금은 멤버 참여 여부를 querydsl에서 처리를 해서 해당 메서드를 사용하지 않는데 제가 바꾸고 다시 원복을 안시켜놓았네요..

2024-02-13 10:08 UTC, alex052525 approved these changes

2024-02-13 13:27 UTC, kellykhy approved these changes
확인했습니다

2024-02-13 21:06 UTC, merged