🐛 Fix: 공동구매 참여 시, 게시물 주최자는 참여할 수 없게끔 개선
moa-moa-service/moamoa-backend pull request #73
Opened 2024-02-11 06:11 UTC by alex052525

## <i>PULL REQUEST</i>

### 🎋 작업중인 브랜치
- fix/65

### 💡 작업동기
- 게시물 주최자가 해당 게시물에 참여자로 참가할 수 있는 문제 발생

### 🔑 주요 변경사항
- 주최자가 본인이 주최한 게시물에 참여하려고 할 때, 예외 처리 로직 구현 

### 관련 이슈
https://github.com/moa-moa-service/moamoa-backend/issues/65

2024-02-12 07:14 UTC, yjsmk0902 requested changes
`joinPost` 로직의 역할이 주최자 뿐아니라, 이미 참여하고 있는 참여자도 참여신청을 할 수 없도록 개선해야할 것 같습니다.

코멘트 확인부탁드립니다~!!

2024-02-12 07:14 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
> +    public boolean IsPostAuthor(Member authMember, Post post) {
`CamelCase`에 따른 메서드 네이밍의 수정이 필요해보입니다.

2024-02-12 07:14 UTC, yjsmk0902 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
>      public AddMemberPostResult joinPost(Long memberId, Long postId) {
파라미터로 건네받은 `memberId`와 `postId`를 가진 `memberPost`의 존재 여부를 통해 참여를 원하는 유저의 주최 여부에 상관없이 참여가 가능한 상황인지 판단해주는 것이 좋을 것 같습니다.

2024-02-13 09:46 UTC, shihan00321 approved these changes
👍

2024-02-13 13:27 UTC, kellykhy approved these changes
확인했습니다!

2024-02-14 12:24 UTC, alex052525 commented on src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
>      public AddMemberPostResult joinPost(Long memberId, Long postId) {
수정완료했습니다!

2024-02-14 18:58 UTC, yjsmk0902 approved these changes

2024-02-14 19:04 UTC, merged